# Generated by Django 4.2.1 on 2023-06-11 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Number')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('month', models.CharField(max_length=20, null=True, verbose_name='Month')),
                ('year', models.CharField(max_length=20, null=True, verbose_name='Year')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now=True)),
                ('fullName', models.CharField(max_length=200, null=True, verbose_name='Full name')),
                ('email', models.EmailField(default='anonim@mail.ru', max_length=254)),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Phone')),
                ('deliveryType', models.CharField(max_length=100, null=True, verbose_name='Способ доставки')),
                ('paymentType', models.CharField(max_length=100, null=True, verbose_name='Способ оплаты')),
                ('totalCost', models.FloatField(blank=True, default=1)),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Статус заказа')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('products', models.ManyToManyField(related_name='products', to='app_goods.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
