# Generated by Django 4.2.1 on 2023-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='catalog',
            name='subcategories',
            field=models.ManyToManyField(related_name='subcategory', to='app_goods.subcategory', verbose_name='Подкатегория'),
        ),
    ]
