# Generated by Django 4.2.1 on 2023-06-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_remove_catalog_subcategories_catalog_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='items',
        ),
    ]
