# Generated by Django 4.2.1 on 2023-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_remove_catalog_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='items',
            field=models.ManyToManyField(related_name='items', to='app_goods.product'),
        ),
    ]
